# Generated by Django 5.0.6 on 2024-07-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_post", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("req_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-req_time"],
            },
        ),
    ]
